root@cb9a06a73734:/etc/ansible# cat pentest.yml
---
- name: Config Web VM with Docker
  hosts: webservers
  become: true
  tasks:

  - name: docker.io on the VM
    apt:
      update_cache: yes
      name: docker.io
      state: present


  - name: Install pip3
    apt:
      name: python3-pip
      state: present


  - name: Install Python Docker module
    pip:
      name: docker
      state: present


  - name: download and than launch a docker web container
    docker_container:
      name: dvwa
      image: cyberxsecurity/dvwa
      state: started
      published_ports: 80:80


  - name: Enable the Docker service itself
    systemd:
      name: docker
      enabled: yes
root@cb9a06a73734:/etc/ansible#
